// repository orchestration service
// manages bare git repository lifecycle on disk
// configures server-side hooks for auto-deployments
// handles directory safety and path traversal protection
// reconciles database records with filesystem state

import path from 'node:path';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';

const GIT_BIN = process.env.GIT_BIN_PATH || 'git';

import { RepoRepository, RepoRow } from './repo.repository';
import { createError } from '../../middleware/errorHandler';
import { logger } from '../../lib/logger';
import { bustDeploymentCache, bustLocalServeCache } from '../../lib/cacheBust';


const REPOS_ROOT = process.env.REPOS_ROOT ?? '/repos';

// valid repo name regex
const REPO_NAME_RE = /^[a-zA-Z0-9._-]{1,100}$/;

// valid username regex
const USERNAME_SAFE_RE = /^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$|^[a-zA-Z0-9]$/;

// assert that path remains within base directory
function assertSafePath(resolvedPath: string, base: string): void {
  const normalBase = path.resolve(base);
  const normalPath = path.resolve(resolvedPath);
  if (!normalPath.startsWith(normalBase + path.sep) && normalPath !== normalBase) {
    throw createError(400, 'Path traversal detected');
  }
}

// internal secret for hook authorization
const INTERNAL_SECRET = (() => {
  const val = process.env.INTERNAL_SECRET;
  if (!val) {
    logger.warn('[RepoFactory] INTERNAL_SECRET is not set  post-receive hooks will not be able to trigger deployments');
    return crypto.randomBytes(32).toString('hex');
  }
  return val;
})();

// base url for post-receive hook calls
const INTERNAL_BASE_URL = process.env.INTERNAL_BASE_URL ?? 'http://localhost:3000';


// shell script content for post-receive hook
function buildPostReceiveHook(username: string, repoName: string): string {
  return String.raw`#!/bin/sh
# post-receive hook  auto-deploy on push to main/master
# generated by gitanic repositoryfactory
# do not edit manually

GITANIC_INTERNAL_URL="${INTERNAL_BASE_URL}/internal/deploy"
GITANIC_SECRET="${INTERNAL_SECRET}"
GITANIC_USERNAME="${username}"
GITANIC_REPO="${repoName}"

while read oldsha newsha refname; do
  branch=$(echo "$refname" | sed 's|refs/heads/||')

  if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
    echo "[gitanic] Push to $branch detected  triggering deployment..."

    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
      -X POST "$GITANIC_INTERNAL_URL" \
      -H "Content-Type: application/json" \
      -H "X-Gitanic-Secret: $GITANIC_SECRET" \
      -d "{\"username\":\"$GITANIC_USERNAME\",\"repo\":\"$GITANIC_REPO\",\"branch\":\"$branch\",\"newsha\":\"$newsha\"}")

    if [ "$RESPONSE" = "202" ]; then
      echo "[gitanic] Deployment enqueued successfully."
    else
      echo "[gitanic] Warning: deployment trigger returned HTTP $RESPONSE"
    fi
  fi
done

exit 0
`;
}


export const RepoFactory = {
  // atomically initialize a bare git repository
  init(username: string, repoName: string): string {
    // input validation
    if (!USERNAME_SAFE_RE.test(username)) {
      throw createError(400, 'Invalid username');
    }
    if (!REPO_NAME_RE.test(repoName)) {
      throw createError(400, 'Invalid repository name');
    }

    const userDir  = path.join(REPOS_ROOT, username);
    const finalPath = path.join(userDir, `${repoName}.git`);
    assertSafePath(finalPath, REPOS_ROOT);

    const tmpPath   = path.join(userDir, `.tmp-${crypto.randomUUID()}`);

    // ensure user directory exists
    fs.mkdirSync(userDir, { recursive: true });

    try {
      // step 1  git init --bare into temp dir
      execFileSync(GIT_BIN, ['init', '--bare', '--initial-branch=main', tmpPath], {
        stdio: 'pipe',
        timeout: 15_000,
      });

        execFileSync(GIT_BIN, ['config', 'http.receivepack', 'true'], {
          cwd: tmpPath,
          stdio: 'pipe',
          timeout: 5_000,
        });

      // step 2  install hooks
      const hooksDir   = path.join(tmpPath, 'hooks');
      const postHookPath   = path.join(hooksDir, 'post-receive');
      const postHookScript = buildPostReceiveHook(username, repoName);
      fs.writeFileSync(postHookPath, postHookScript, { encoding: 'utf8', mode: 0o755 });

      const preHookPath   = path.join(hooksDir, 'pre-receive');
      const preHookScript = `#!/bin/sh
# pre-receive hook to block forbidden directories
while read oldsha newsha refname; do
  # check if it's a delete branch operation
  if [ "$newsha" = "0000000000000000000000000000000000000000" ]; then
    continue
  fi

  if [ "$oldsha" = "0000000000000000000000000000000000000000" ]; then
    FILES=$(git ls-tree -r --name-only "$newsha")
  else
    FILES=$(git diff-tree -r --name-only --no-commit-id "$oldsha" "$newsha")
  fi

  for file in $FILES; do
    case "$file" in
      *node_modules/*|*bower_components/*|*__pycache__/*|*.py[cod]|*$py.class|*.env|*/.env|*.env.*|*.log|*-debug.log*|*-error.log*|*.DS_Store|*/.DS_Store|*Thumbs.db|*.idea/*|*.vscode/*|*.suo|*.ntvs*|*.njsproj|*.sln|*.sw?|*dist/*|*build/*|*out/*|*.next/*|*.nuxt/*|*.cache/*|*coverage/*|*.nyc_output/*|*.pem|*.key|*.p12|*.pfx|*.sqlite|package-lock.json|yarn.lock|pnpm-lock.yaml)
        echo "================================================================" >&2
        echo " ERROR: Push rejected by Gitanic" >&2
        echo "================================================================" >&2
        echo " Forbidden file detected: $file" >&2
        echo "" >&2
        echo " build outputs, dependencies, ide config, and secrets are not accepted." >&2
        echo " please add them to your .gitignore and remove them from git." >&2
        echo "================================================================" >&2
        exit 1
        ;;
    esac
  done
done
exit 0
`;
      fs.writeFileSync(preHookPath, preHookScript, { encoding: 'utf8', mode: 0o755 });

      // atomic rename to final path
      // defensively clean up any orphaned directory with the exact same name
      if (fs.existsSync(finalPath)) {
        fs.rmSync(finalPath, { recursive: true, force: true });
      }
      fs.renameSync(tmpPath, finalPath);

      logger.info(`[RepoFactory] Bare repo created at ${finalPath}`, {
        meta: { username, repoName },
      });

      return finalPath;

    } catch (err) {
      // cleanup temp dir on failure
      try { fs.rmSync(tmpPath, { recursive: true, force: true }); } catch (cleanErr) {
        logger.warn(`[RepoFactory] Failed to clean up temp dir ${tmpPath}: ${String(cleanErr)}`);
      }
      throw err;
    }
  },

  // remove bare repo directory
  destroy(username: string, repoName: string): void {
    if (!/^[a-zA-Z0-9-]+$/.test(username) || !/^[a-zA-Z0-9-]+$/.test(repoName)) return;
    const repoPath = RepoFactory.repoPath(username, repoName);
    if (!fs.existsSync(repoPath)) return; // already gone
    fs.rmSync(repoPath, { recursive: true, force: true });
    logger.info(`[RepoFactory] Removed repo directory ${repoPath}`, {
      meta: { username, repoName },
    });
  },

  // rename bare repo directory
  rename(username: string, oldName: string, newName: string): void {
    const oldPath = RepoFactory.repoPath(username, oldName);
    const newPath = RepoFactory.repoPath(username, newName);
    
    // Use statSync instead of existsSync to avoid TOCTOU on the destination directory check
    try {
      fs.statSync(newPath);
      throw createError(409, `Destination directory already exists`);
    } catch (err: any) {
      if (err.status === 409) throw err;
      // If it throws ENOENT or something else, destination does not exist (expected)
    }

    // Try-catch the direct rename to securely assess file operations
    try {
      fs.renameSync(oldPath, newPath);
    } catch (err: any) {
      if (err.code === 'ENOENT') {
        throw createError(404, `Repository directory not found`);
      }
      throw err;
    }

    const postHookPath = path.join(newPath, 'hooks', 'post-receive');
    try {
      fs.accessSync(postHookPath, fs.constants.F_OK);
      const postHookScript = buildPostReceiveHook(username, newName);
      fs.writeFileSync(postHookPath, postHookScript, { encoding: 'utf8', mode: 0o755 });
    } catch {
      // ignore if hook path does not exist
    }

    logger.info(`[RepoFactory] Renamed repo directory ${oldPath} to ${newPath}`, {
      meta: { username, oldName, newName },
    });
  },

  // absolute filesystem path for a repo
  repoPath(username: string, repoName: string): string {
    if (!/^[a-zA-Z0-9._-]+$/.test(repoName)) {
      throw createError(400, 'Invalid repository name format');
    }
    if (!/^[a-zA-Z0-9-]+$/.test(username)) {
      throw createError(400, 'Invalid username format');
    }
    const p = path.join(REPOS_ROOT, username.toLowerCase(), `${repoName.toLowerCase()}.git`);
    assertSafePath(p, REPOS_ROOT);
    return p;
  },

  // check if bare repo directory exists
  exists(username: string, repoName: string): boolean {
    return fs.existsSync(RepoFactory.repoPath(username, repoName));
  },

  // path to post-receive hook
  hookPath(username: string, repoName: string): string {
    return path.join(RepoFactory.repoPath(username, repoName), 'hooks', 'post-receive');
  },
};


export interface CreateRepoResult {
  id: string;
  name: string;
  owner_id: string;
  auto_deploy_enabled: boolean;
  active_deployment_id: string | null;
  created_at: string;
  updated_at?: string;
  git_url: string;
}

export const RepoService = {
  // create repository
  async create(
    userId: string,
    username: string,
    repoName: string
  ): Promise<CreateRepoResult> {

    const normalizedRepoName = repoName.toLowerCase();
    const normalizedUsername = username.toLowerCase();

    if (!normalizedRepoName || !REPO_NAME_RE.test(normalizedRepoName)) {
      throw createError(
        400,
        'Repository name must be 1–100 characters and contain only letters, numbers, hyphens, underscores, or dots'
      );
    }
    if (normalizedRepoName.startsWith('.') || normalizedRepoName.endsWith('.')) {
      throw createError(400, 'Repository name cannot start or end with a dot');
    }

    const existing = await RepoRepository.findByOwnerAndName(userId, normalizedRepoName);
    if (existing) {
      throw createError(409, `Repository "${normalizedRepoName}" already exists`);
    }
    let row: RepoRow;
    try {
      row = await RepoRepository.create({ name: normalizedRepoName, owner_id: userId });
    } catch (err: unknown) {
      const pgErr = err as { code?: string };
      if (pgErr.code === '23505') {
        throw createError(409, `Repository "${normalizedRepoName}" already exists`);
      }
      throw err;
    }

    try {
      RepoFactory.init(normalizedUsername, normalizedRepoName);
    } catch (err) {
      logger.error('[RepoService] Filesystem init failed  rolling back DB row', {
        userId,
        repoId: row.id,
        meta: { error: String(err) },
      });
      await RepoRepository.delete(row.id, userId).catch(() => undefined);
      throw createError(500, `Failed to initialise git repository on server: ${String(err)}`);
    }

    return { ...row, git_url: buildGitUrl(normalizedUsername, normalizedRepoName) };
  },

  // list all user repos
  async list(userId: string, username: string): Promise<CreateRepoResult[]> {
    const rows = await RepoRepository.findAllByOwner(userId);
    return rows.map((r) => ({ ...r, git_url: buildGitUrl(username, r.name) }));
  },

  // get a single user repo by name
  async getByName(userId: string, username: string, repoName: string): Promise<CreateRepoResult> {
    const row = await RepoRepository.findByOwnerAndName(userId, repoName);
    if (!row) throw createError(404, `Repository "${repoName}" not found`);
    return { ...row, git_url: buildGitUrl(username, repoName) };
  },

  // resolve active deployment id
  async resolveDeploymentId(username: string, repoName: string): Promise<string | null> {
    const row = await RepoRepository.findByUsernameAndRepoName(username, repoName);
    return row?.active_deployment_id ?? null;
  },

  // delete repository
  async delete(userId: string, username: string, repoName: string): Promise<void> {
    const row = await RepoRepository.findByOwnerAndName(userId, repoName);
    if (!row) throw createError(404, `Repository "${repoName}" not found`);

    const deleted = await RepoRepository.delete(row.id, userId);
    if (!deleted) throw createError(404, `Repository "${repoName}" not found`);

    try {
      RepoFactory.destroy(username, repoName);
    } catch (err) {
      // db is already committed  log but don't re-throw
      logger.warn(`[RepoService] FS removal failed for ${repoName}: ${String(err)}`, {
        userId,
        repoId: row.id,
      });
    }
  },

  // rename repository
  async rename(userId: string, username: string, oldName: string, newName: string): Promise<void> {
    const normalizedOldName = oldName.toLowerCase();
    const normalizedNewName = newName.toLowerCase();

    if (normalizedOldName === normalizedNewName) return;

    if (!normalizedNewName || !REPO_NAME_RE.test(normalizedNewName)) {
      throw createError(
        400,
        'Repository name must be 1–100 characters and contain only letters, numbers, hyphens, underscores, or dots'
      );
    }
    if (normalizedNewName.startsWith('.') || normalizedNewName.endsWith('.')) {
      throw createError(400, 'Repository name cannot start or end with a dot');
    }

    const repo = await RepoRepository.findByOwnerAndName(userId, normalizedOldName);
    if (!repo) throw createError(404, `Repository "${normalizedOldName}" not found`);

    const existingNew = await RepoRepository.findByOwnerAndName(userId, normalizedNewName);
    if (existingNew) throw createError(409, `Repository "${normalizedNewName}" already exists`);

    try {
      RepoFactory.rename(username, normalizedOldName, normalizedNewName);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      throw createError(500, `Failed to rename git directory: ${msg}`);
    }

    try {
      await RepoRepository.updateName(repo.id, userId, normalizedNewName);
    } catch (err: unknown) {
      try {
        RepoFactory.rename(username, normalizedNewName, normalizedOldName);
      } catch (e) {
        logger.error(`[RepoService] FS rollback failed after DB fail for ${normalizedOldName}->${normalizedNewName}`, { meta: { error: String(e) } });
      }
      throw createError(500, `Failed to update database record: ${err instanceof Error ? err.message : String(err)}`);
    }

    bustDeploymentCache(username).catch(() => undefined);
    bustLocalServeCache(username).catch(() => undefined);
  },
};

// reconcile db records with filesystem
export async function reconcileReposOnDisk(): Promise<void> {
  const defaultSync = process.env.NODE_ENV === 'production' ? 'false' : 'true';
  const shouldSync = (process.env.SYNC_REPOS_ON_STARTUP ?? defaultSync).toLowerCase() === 'true';

  if (!shouldSync) {
    return;
  }

  const repos = await RepoRepository.findAllWithOwnerUsername();
  let created = 0;

  for (const repo of repos) {
    if (RepoFactory.exists(repo.username, repo.name)) {
      continue;
    }

    try {
      RepoFactory.init(repo.username, repo.name);
      created += 1;
      logger.info(`[RepoBootstrap] Created missing bare repo for ${repo.username}/${repo.name}`);
    } catch (err) {
      logger.error(`[RepoBootstrap] Failed to create bare repo for ${repo.username}/${repo.name}: ${String(err)}`);
    }
  }

  logger.info('[RepoBootstrap] Repository reconcile complete', {
    meta: { scanned: repos.length, created },
  });
}


function buildGitUrl(username: string, repoName: string): string {
  const host = process.env.GIT_HOST ?? 'localhost:3000';
  // use https for non-localhost hosts  railway redirects http -> https which strips credentials
  const scheme = host.startsWith('localhost') || host.startsWith('127.') ? 'http' : 'https';
  return `${scheme}://${host}/git/${username}/${repoName}.git`;
}
