/**
 * repo.service.ts — Repository management: Service Layer + Factory Pattern
 *
 * RepositoryFactory.init() is ATOMIC:
 *   1. git init --bare into a TEMP directory (/repos/{user}/.tmp-{uuid})
 *   2. Install post-receive hook into the temp dir
 *   3. fs.renameSync() into final path (single syscall — atomic on same FS)
 *   On any failure the temp dir is cleaned up; the final path is never created.
 *
 * RepoService.create() is also atomic at the service level:
 *   - DB row created first
 *   - Filesystem init runs second; DB row is rolled back on FS failure
 *
 * Architecture: Service Layer + Factory Pattern
 */

import path from 'path';
import fs from 'fs';
import { execFileSync } from 'child_process';
import crypto from 'crypto';
import { RepoRepository, RepoRow } from './repo.repository';
import { createError } from '../../middleware/errorHandler';
import { logger } from '../../lib/logger';

// ── Constants ─────────────────────────────────────────────────────────────────

/** Root directory where bare git repos are stored on Railway filesystem. */
const REPOS_ROOT = process.env.REPOS_ROOT ?? '/repos';

/** Valid repo name: alphanumeric, hyphen, underscore, dot; 1–100 chars. */
const REPO_NAME_RE = /^[a-zA-Z0-9._-]{1,100}$/;

/**
 * Shared secret for /internal/deploy.
 * Set INTERNAL_SECRET in env; must match what the hook sends.
 */
const INTERNAL_SECRET = process.env.INTERNAL_SECRET ?? 'change-me-internal-secret';

/** The base URL the post-receive hook POSTs to. */
const INTERNAL_BASE_URL = process.env.INTERNAL_BASE_URL ?? 'http://localhost:3000';

// ── Post-receive hook script template ────────────────────────────────────────

/**
 * Generates the shell script content for the post-receive hook.
 *
 * The hook:
 *   1. Reads stdin (oldSha newSha refname) from git
 *   2. Detects if the push is to refs/heads/main
 *   3. POSTs to /internal/deploy with the repo + user identifiers
 *      using curl (always available on Railway / Alpine Linux)
 */
function buildPostReceiveHook(username: string, repoName: string): string {
  return `#!/bin/sh
# post-receive hook — auto-deploy on push to main/master
# Generated by Gitanic RepositoryFactory
# DO NOT EDIT MANUALLY

GITANIC_INTERNAL_URL="${INTERNAL_BASE_URL}/internal/deploy"
GITANIC_SECRET="${INTERNAL_SECRET}"
GITANIC_USERNAME="${username}"
GITANIC_REPO="${repoName}"

while read oldsha newsha refname; do
  branch=$(echo "$refname" | sed 's|refs/heads/||')

  if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
    echo "[gitanic] Push to $branch detected — triggering deployment..."

    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \\
      -X POST "$GITANIC_INTERNAL_URL" \\
      -H "Content-Type: application/json" \\
      -H "X-Gitanic-Secret: $GITANIC_SECRET" \\
      -d "{\\"username\\":\\"$GITANIC_USERNAME\\",\\"repo\\":\\"$GITANIC_REPO\\",\\"branch\\":\\"$branch\\",\\"newsha\\":\\"$newsha\\"}")

    if [ "$RESPONSE" = "202" ]; then
      echo "[gitanic] Deployment enqueued successfully."
    else
      echo "[gitanic] Warning: deployment trigger returned HTTP $RESPONSE"
    fi
  fi
done

exit 0
`;
}

// ── RepositoryFactory ─────────────────────────────────────────────────────────

export const RepoFactory = {
  /**
   * ATOMICALLY initialise a bare git repository.
   *
   * Strategy:
   *   1. Work inside a temp directory on the SAME filesystem partition
   *      (so rename is guaranteed to be atomic)
   *   2. git init --bare <tmpdir>
   *   3. Install post-receive hook (chmod +x)
   *   4. Rename tmpdir → final path (atomic on POSIX; best-effort on Windows)
   *
   * Throws on any failure. Temp directory is always cleaned up.
   */
  init(username: string, repoName: string): string {
    const userDir  = path.join(REPOS_ROOT, username);
    const finalPath = path.join(userDir, `${repoName}.git`);
    const tmpPath   = path.join(userDir, `.tmp-${crypto.randomUUID()}`);

    // Ensure user directory exists
    fs.mkdirSync(userDir, { recursive: true });

    try {
      // Step 1 — git init --bare into temp dir
      execFileSync('git', ['init', '--bare', '--initial-branch=main', tmpPath], {
        stdio: 'pipe',
        timeout: 15_000,
      });

      // Step 2 — install post-receive hook
      const hooksDir  = path.join(tmpPath, 'hooks');
      const hookPath  = path.join(hooksDir, 'post-receive');
      const hookScript = buildPostReceiveHook(username, repoName);

      fs.writeFileSync(hookPath, hookScript, { encoding: 'utf8', mode: 0o755 });

      // Step 3 — atomic rename to final path
      //   fs.renameSync is a single syscall (rename(2)) — atomic on POSIX
      //   when src and dst are on the same filesystem.
      // Defensively clean up any orphaned directory with the exact same name
      if (fs.existsSync(finalPath)) {
        fs.rmSync(finalPath, { recursive: true, force: true });
      }
      fs.renameSync(tmpPath, finalPath);

      logger.info(`[RepoFactory] Bare repo created at ${finalPath}`, {
        meta: { username, repoName },
      });

      return finalPath;

    } catch (err) {
      // Clean up temp dir on any failure — never leave a partial repo
      try { fs.rmSync(tmpPath, { recursive: true, force: true }); } catch { /* ignore */ }
      throw err;
    }
  },

  /**
   * Remove the bare repo directory synchronously.
   * Called during DELETE /api/repos/:name after DB row is deleted.
   */
  destroy(username: string, repoName: string): void {
    const repoPath = RepoFactory.repoPath(username, repoName);
    if (!fs.existsSync(repoPath)) return; // already gone
    fs.rmSync(repoPath, { recursive: true, force: true });
    logger.info(`[RepoFactory] Removed repo directory ${repoPath}`, {
      meta: { username, repoName },
    });
  },

  /** Absolute filesystem path for a given repo. */
  repoPath(username: string, repoName: string): string {
    return path.join(REPOS_ROOT, username, `${repoName}.git`);
  },

  /** Check whether the bare repo directory exists on disk. */
  exists(username: string, repoName: string): boolean {
    return fs.existsSync(RepoFactory.repoPath(username, repoName));
  },

  /** Path to the post-receive hook for an existing repo. */
  hookPath(username: string, repoName: string): string {
    return path.join(RepoFactory.repoPath(username, repoName), 'hooks', 'post-receive');
  },
};

// ── RepoService ───────────────────────────────────────────────────────────────

export interface CreateRepoResult {
  id: string;
  name: string;
  owner_id: string;
  auto_deploy_enabled: boolean;
  active_deployment_id: string | null;
  created_at: string;
  git_url: string;
}

export const RepoService = {
  /**
   * Create a repository — atomic in two phases:
   *   Phase A: DB row insert (rolls back on FS failure)
   *   Phase B: Filesystem RepositoryFactory.init() (atomic rename inside)
   */
  async create(
    userId: string,
    username: string,
    repoName: string
  ): Promise<CreateRepoResult> {

    const normalizedRepoName = repoName.toLowerCase();
    const normalizedUsername = username.toLowerCase();

    // ── Validate ───────────────────────────────────────────────────────────────
    if (!normalizedRepoName || !REPO_NAME_RE.test(normalizedRepoName)) {
      throw createError(
        400,
        'Repository name must be 1–100 characters and contain only letters, numbers, hyphens, underscores, or dots'
      );
    }
    if (normalizedRepoName.startsWith('.') || normalizedRepoName.endsWith('.')) {
      throw createError(400, 'Repository name cannot start or end with a dot');
    }

    // ── Uniqueness pre-check ──────────────────────────────────────────────────
    const existing = await RepoRepository.findByOwnerAndName(userId, normalizedRepoName);
    if (existing) {
      throw createError(409, `Repository "${normalizedRepoName}" already exists`);
    }

    // ── Phase A: DB row ───────────────────────────────────────────────────────
    let row: RepoRow;
    try {
      row = await RepoRepository.create({ name: normalizedRepoName, owner_id: userId });
    } catch (err: unknown) {
      const pgErr = err as { code?: string };
      if (pgErr.code === '23505') {
        throw createError(409, `Repository "${normalizedRepoName}" already exists`);
      }
      throw err;
    }

    // ── Phase B: Filesystem (atomic) ──────────────────────────────────────────
    try {
      RepoFactory.init(normalizedUsername, normalizedRepoName);
    } catch (err) {
      logger.error('[RepoService] Filesystem init failed — rolling back DB row', {
        userId,
        repoId: row.id,
        meta: { error: String(err) },
      });
      await RepoRepository.delete(row.id, userId).catch(() => undefined);
      throw createError(500, `Failed to initialise git repository on server: ${String(err)}`);
    }

    return { ...row, git_url: buildGitUrl(normalizedUsername, normalizedRepoName) };
  },

  /** List all repos for the authenticated user. */
  async list(userId: string, username: string): Promise<CreateRepoResult[]> {
    const rows = await RepoRepository.findAllByOwner(userId);
    return rows.map((r) => ({ ...r, git_url: buildGitUrl(username, r.name) }));
  },

  /** Get a single repo by name for the authenticated user. */
  async getByName(userId: string, username: string, repoName: string): Promise<CreateRepoResult> {
    const row = await RepoRepository.findByOwnerAndName(userId, repoName);
    if (!row) throw createError(404, `Repository "${repoName}" not found`);
    return { ...row, git_url: buildGitUrl(username, repoName) };
  },

  /**
   * Delete a repository:
   *   1. DB row deleted (CASCADE removes deployments + logs)
   *   2. Filesystem directory removed SYNCHRONOUSLY
   *      (avoids leaving orphaned dirs if process restarts mid-cleanup)
   */
  async delete(userId: string, username: string, repoName: string): Promise<void> {
    const row = await RepoRepository.findByOwnerAndName(userId, repoName);
    if (!row) throw createError(404, `Repository "${repoName}" not found`);

    const deleted = await RepoRepository.delete(row.id, userId);
    if (!deleted) throw createError(404, `Repository "${repoName}" not found`);

    // Synchronous FS removal — intentional (see jsdoc above)
    try {
      RepoFactory.destroy(username, repoName);
    } catch (err) {
      // DB is already committed — log but don't re-throw
      logger.warn(`[RepoService] FS removal failed for ${repoName}: ${String(err)}`, {
        userId,
        repoId: row.id,
      });
    }
  },
};

/**
 * Reconcile DB repositories with filesystem bare repos.
 *
 * This is primarily useful in local development where seed SQL may insert
 * repository rows directly without running RepositoryFactory.
 */
export async function reconcileReposOnDisk(): Promise<void> {
  const defaultSync = process.env.NODE_ENV === 'production' ? 'false' : 'true';
  const shouldSync = (process.env.SYNC_REPOS_ON_STARTUP ?? defaultSync).toLowerCase() === 'true';

  if (!shouldSync) {
    return;
  }

  const repos = await RepoRepository.findAllWithOwnerUsername();
  let created = 0;

  for (const repo of repos) {
    if (RepoFactory.exists(repo.username, repo.name)) {
      continue;
    }

    try {
      RepoFactory.init(repo.username, repo.name);
      created += 1;
      logger.info(`[RepoBootstrap] Created missing bare repo for ${repo.username}/${repo.name}`);
    } catch (err) {
      logger.error(`[RepoBootstrap] Failed to create bare repo for ${repo.username}/${repo.name}: ${String(err)}`);
    }
  }

  logger.info('[RepoBootstrap] Repository reconcile complete', {
    meta: { scanned: repos.length, created },
  });
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function buildGitUrl(username: string, repoName: string): string {
  const host = process.env.GIT_HOST ?? 'localhost:3000';
  return `http://${host}/git/${username}/${repoName}.git`;
}
